module.exports = {
    // Authentication
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    USER_LOGIN_FAILED: "USER_LOGIN_FAILED",

    // MFA
    MFA_ENABLED: "MFA_ENABLED",
    MFA_DISABLED: "MFA_DISABLED",
    MFA_VERIFIED: "MFA_VERIFIED",
    MFA_VERIFY_FAILED: "MFA_VERIFY_FAILED",

    // Sessions
    SESSION_CREATED: "SESSION_CREATED",
    SESSION_REVOKED: "SESSION_REVOKED",
    SESSION_EXPIRED: "SESSION_EXPIRED",
    SESSION_REVOKED_ALL: "SESSION_REVOKED_ALL",

    // Users
    USER_CREATED: "USER_CREATED",
    USER_UPDATED: "USER_UPDATED",
    USER_DELETED: "USER_DELETED",

    // Roles
    ROLE_CREATED: "ROLE_CREATED",
    ROLE_UPDATED: "ROLE_UPDATED",
    ROLE_DELETED: "ROLE_DELETED",
    ROLE_ASSIGNED: "ROLE_ASSIGNED",
    ROLE_REMOVED: "ROLE_REMOVED",

    // Permissions
    PERMISSION_CREATED: "PERMISSION_CREATED",
    PERMISSION_UPDATED: "PERMISSION_UPDATED",
    PERMISSION_DELETED: "PERMISSION_DELETED",
    PERMISSION_GRANTED: "PERMISSION_GRANTED",
    PERMISSION_REVOKED: "PERMISSION_REVOKED",

    // Applications
    APPLICATION_CREATED: "APPLICATION_CREATED",
    APPLICATION_UPDATED: "APPLICATION_UPDATED",
    APPLICATION_DELETED: "APPLICATION_DELETED",

    // SSO
    SSO_LOGIN: "SSO_LOGIN",
    SSO_LOGOUT: "SSO_LOGOUT",
    OAUTH_CODE_ISSUED: "OAUTH_CODE_ISSUED",
    OAUTH_TOKEN_ISSUED: "OAUTH_TOKEN_ISSUED",

    // Marketplace
    APPLICATION_PUBLISHED: "APPLICATION_PUBLISHED",
    APPLICATION_INSTALLED: "APPLICATION_INSTALLED",
    APPLICATION_UNINSTALLED: "APPLICATION_UNINSTALLED",
    INSTALLATION_FAILED: "INSTALLATION_FAILED",

    // Subscriptions
    PLAN_CREATED: "PLAN_CREATED",
    PLAN_UPDATED: "PLAN_UPDATED",
    PLAN_ASSIGNED: "PLAN_ASSIGNED",
    PLAN_UPGRADED: "PLAN_UPGRADED",
    PLAN_DOWNGRADED: "PLAN_DOWNGRADED",
    SUBSCRIPTION_CANCELLED: "SUBSCRIPTION_CANCELLED",
    USAGE_LIMIT_REACHED: "USAGE_LIMIT_REACHED",
    LICENSE_CREATED: "LICENSE_CREATED",
    LICENSE_EXPIRED: "LICENSE_EXPIRED",
    INVOICE_CREATED: "INVOICE_CREATED",
    INVOICE_PAID: "INVOICE_PAID",
    PAYMENT_FAILED: "PAYMENT_FAILED",
    SUBSCRIPTION_RENEWED: "SUBSCRIPTION_RENEWED",
    USAGE_BILLED: "USAGE_BILLED",

    // Workflows
    WORKFLOW_CREATED: "WORKFLOW_CREATED",
    WORKFLOW_UPDATED: "WORKFLOW_UPDATED",
    WORKFLOW_DELETED: "WORKFLOW_DELETED",
    WORKFLOW_EXECUTED: "WORKFLOW_EXECUTED",
    WORKFLOW_FAILED: "WORKFLOW_FAILED",
    WORKFLOW_RETRIED: "WORKFLOW_RETRIED",
    WORKFLOW_DISABLED: "WORKFLOW_DISABLED",

    // Event Bus
    EVENT_PUBLISHED: "EVENT_PUBLISHED",
    EVENT_DELIVERED: "EVENT_DELIVERED",
    EVENT_FAILED: "EVENT_FAILED",
    EVENT_REPLAYED: "EVENT_REPLAYED",
    SUBSCRIPTION_CREATED: "SUBSCRIPTION_CREATED",
    SUBSCRIPTION_REMOVED: "SUBSCRIPTION_REMOVED",

    // Governance & Compliance
    APPROVAL_REQUESTED: "APPROVAL_REQUESTED",
    APPROVAL_GRANTED: "APPROVAL_GRANTED",
    APPROVAL_REJECTED: "APPROVAL_REJECTED",
    POLICY_CREATED: "POLICY_CREATED",
    POLICY_UPDATED: "POLICY_UPDATED",
    DELEGATED_ADMIN_ASSIGNED: "DELEGATED_ADMIN_ASSIGNED",
    COMPLIANCE_REVIEW_COMPLETED: "COMPLIANCE_REVIEW_COMPLETED",

    // AI Copilot
    AI_QUERY_EXECUTED: "AI_QUERY_EXECUTED",
    AI_ACTION_DRAFTED: "AI_ACTION_DRAFTED",
    AI_ACTION_APPROVED: "AI_ACTION_APPROVED",
    AI_ACTION_REJECTED: "AI_ACTION_REJECTED",
    AI_ACTION_EXECUTED: "AI_ACTION_EXECUTED",

    // Infrastructure & HA/DR
    REGION_CREATED: "REGION_CREATED",
    REGION_STATUS_CHANGED: "REGION_STATUS_CHANGED",
    CLUSTER_HEALTH_CHANGED: "CLUSTER_HEALTH_CHANGED",
    FAILOVER_TRIGGERED: "FAILOVER_TRIGGERED",
    FAILOVER_COMPLETED: "FAILOVER_COMPLETED",
    BACKUP_CREATED: "BACKUP_CREATED",
    BACKUP_RESTORED: "BACKUP_RESTORED",
    RECOVERY_DRILL_STARTED: "RECOVERY_DRILL_STARTED",
    RECOVERY_COMPLETED: "RECOVERY_COMPLETED",

    // Developer Ecosystem
    API_KEY_CREATED: "API_KEY_CREATED",
    API_KEY_ROTATED: "API_KEY_ROTATED",
    API_KEY_REVOKED: "API_KEY_REVOKED",
    WEBHOOK_REGISTERED: "WEBHOOK_REGISTERED",
    WEBHOOK_DELIVERED: "WEBHOOK_DELIVERED",
    API_LIMIT_EXCEEDED: "API_LIMIT_EXCEEDED",
    DEVELOPER_REGISTERED: "DEVELOPER_REGISTERED"
};
